# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
#image: busybox:latest

stages:
  - create_VM
  - build
  - deploy
  - health_check
  - test
create1:
  stage: create_VM
  script:
    - ssh -t user@10.0.0.161
    - exit
build1:
  stage: build
  script:
    - ping 10.0.0.1 -c 1
deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"
test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"
test3:
  stage: test
  script:
  - ping 10.0.2.7 -c 2
